input_data = {'You regularly make new friends.' : 0,
       'You spend a lot of your free time exploring various random topics that pique your interest.' : 0,
       'Seeing other people cry can easily make you feel like you want to cry too.' : 0,
       'You often make a backup plan for a backup plan.' : 0,
       'You usually stay calm, even under a lot of pressure.' : 0,
       'At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.' : 0,
       'You prefer to completely finish one project before starting another.' : 0,
       'You are very sentimental.' : 0,
       'You like to use organizing tools like schedules and lists.' : 0,
       'Even a small mistake can cause you to doubt your overall abilities and knowledge.' : 0,
       'You feel comfortable just walking up to someone you find interesting and striking up a conversation.' : 0,
       'You are not too interested in discussing various interpretations and analyses of creative works.' : 0,
       'You are more inclined to follow your head than your heart.' : 0,
       'You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.' : 0,
       'You rarely worry about whether you make a good impression on people you meet.' : 0,
       'You enjoy participating in group activities.' : 0,
       'You like books and movies that make you come up with your own interpretation of the ending.' : 0,
       'Your happiness comes more from helping others accomplish things than your own accomplishments.' : 0,
       'You are interested in so many things that you find it difficult to choose what to try next.' : 0,
       'You are prone to worrying that things will take a turn for the worse.' : 0,
       'You avoid leadership roles in group settings.' : 0,
       'You are definitely not an artistic type of person.' : 0,
       'You think the world would be a better place if people relied more on rationality and less on their feelings.' : 0,
       'You prefer to do your chores before allowing yourself to relax.' : 0,
       'You enjoy watching people argue.' : 0,
       'You tend to avoid drawing attention to yourself.' : 0,
       'Your mood can change very quickly.' : 0,
       'You lose patience with people who are not as efficient as you.' : 0,
       'You often end up doing things at the last possible moment.' : 0,
       'You have always been fascinated by the question of what, if anything, happens after death.' : 0,
       'You usually prefer to be around others rather than on your own.' : -0,
       'You become bored or lose interest when the discussion gets highly theoretical.' : 0,
       'You find it easy to empathize with a person whose experiences are very different from yours.' : 0,
       'You usually postpone finalizing decisions for as long as possible.' : 0,
       'You rarely second-guess the choices that you have made.' : 0,
       'after a long and exhausting week, a lively social event is just what you need.' : 0,
       'You enjoy going to art museums.' : 0,
       'You often have a hard time understanding other people’s feelings.' : 0,
       'You like to have a to-do list for each day.' : 0,
       'You rarely feel insecure' : 1, 'you avoid making phone calls.' : 0,
       'You often spend a lot of time trying to understand views that are very different from your own.' : 0,
       'In your social circle, you are often the one who contacts your friends and initiates activities.' : 0,
       'If your plans are interrupted, your top priority is to get back on track as soon as possible.' : 0,
       'You are still bothered by mistakes that you made a long time ago.' : 0,
       'You rarely contemplate the reasons for human existence or the meaning of life.' : 0,
       'Your emotions control you more than you control them.' : 0,
       'You take great care not to make people look bad, even when it is completely their fault.' : 0,
       'Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts.' : 0,
       'When someone thinks highly of you, you wonder how long it will take them to feel disappointed in you.' : 0,
       'You would love a job that requires you to work alone most of the time.' : 0,
       'You believe that pondering abstract philosophical questions is a waste of time.' : 0,
       'You feel more drawn to places with busy, bustling atmospheres than quiet, intimate places.' : 0,
       'You know at first glance how someone is feeling.' : 0,
       'You often feel overwhelmed.' : 0,
       'You complete things methodically without skipping over any steps.' : 0,
       'You are very intrigued by things labeled as controversial.' : 0,
       'You would pass along a good opportunity if you thought someone else needed it more.' : 0,
       'You struggle with deadlines.' : 0,
       'You feel confident that things will work out for you.' : 0}


response_map = {
    3: "Fully Agree",
    2: "Partially Agree",
    1: "Slightly Agree",
    0: "Neutral",
    -1: "Slightly Disagree",
    -2: "Partially Disagree",
    -3: "Fully Disagree"
}

personalities = {
    "ESTJ": {
        "kepanjangan": "Extraverted, Sensing, Thinking, Judging",
        "deskripsi": "Orang dengan tipe ESTJ cenderung tegas, terorganisir, dan praktis. Mereka suka mengambil peran pemimpin, menghargai tradisi, dan berpegang pada aturan. Dikenal sebagai 'The Executive' atau 'The Supervisor'.",
        "karakteristik": ["Disiplin", "Bertanggung jawab", "Logis", "Suka struktur", "Konservatif"],
    },
    "ISTJ": {
        "kepanjangan": "Introverted, Sensing, Thinking, Judging",
        "deskripsi": "ISTJ adalah pribadi yang detail-oriented, teratur, dan dapat diandalkan. Mereka menghargai fakta dan tanggung jawab. Dijuluki 'The Inspector' atau 'The Logistician'.",
        "karakteristik": ["Jujur", "Sistematis", "Patuh pada aturan", "Praktis", "Konsisten"],
    },
    "ESFJ": {
        "kepanjangan": "Extraverted, Sensing, Feeling, Judging",
        "deskripsi": "ESFJ adalah orang yang hangat, peduli, dan suka bersosialisasi. Mereka fokus pada harmoni dan kebutuhan orang lain. Dikenal sebagai 'The Consul' atau 'The Caregiver'.",
        "karakteristik": ["Ramah", "Kooperatif", "Tradisional", "Bertanggung jawab sosial", "Suka membantu"],
    },
    "ISFJ": {
        "kepanjangan": "Introverted, Sensing, Feeling, Judging",
        "deskripsi": "ISFJ adalah pribadi yang penuh perhatian, setia, dan protektif terhadap orang terdekat. Mereka dijuluki 'The Defender' atau 'The Protector'.",
        "karakteristik": ["Perhatian", "Sabar", "Reliabel", "Sensitif", "Berdedikasi"],
    },
    "ESTP": {
        "kepanjangan": "Extraverted, Sensing, Thinking, Perceiving",
        "deskripsi": "ESTP adalah tipe yang energik, spontan, dan suka tantangan. Mereka ahli dalam memecahkan masalah secara praktis. Dijuluki 'The Entrepreneur' atau 'The Dynamo'.",
        "karakteristik": ["Berani", "Pintar membaca situasi", "Fleksibel", "Obyektif", "Suka aksi"],
    },
    "ISTP": {
        "kepanjangan": "Introverted, Sensing, Thinking, Perceiving",
        "deskripsi": "ISTP adalah pribadi mandiri yang ahli dalam analisis teknis dan pemecahan masalah. Dikenal sebagai 'The Virtuoso' atau 'The Craftsman'.",
        "karakteristik": ["Tenang", "Logis", "Mekanikal", "Adaptif", "Netral secara emosional"],
    },
    "ESFP": {
        "kepanjangan": "Extraverted, Sensing, Feeling, Perceiving",
        "deskripsi": "ESFP adalah orang yang menyenangkan, spontan, dan suka menjadi pusat perhatian. Mereka dijuluki 'The Entertainer' atau 'The Performer'.",
        "karakteristik": ["Optimis", "Energik", "Sosial", "Penyayang", "Spontan"],
    },
    "ISFP": {
        "kepanjangan": "Introverted, Sensing, Feeling, Perceiving",
        "deskripsi": "ISFP adalah pribadi yang artistik, rendah hati, dan menghargai kebebasan pribadi. Dijuluki 'The Adventurer' atau 'The Artist'.",
        "karakteristik": ["Sensitif", "Kreatif", "Santai", "Setia pada nilai pribadi", "Menghindari konflik"],
    },
    "ENTJ": {
        "kepanjangan": "Extraverted, Intuitive, Thinking, Judging",
        "deskripsi": "ENTJ adalah pemimpin alami yang visioner, tegas, dan strategis. Dikenal sebagai 'The Commander' atau 'The Leader'.",
        "karakteristik": ["Karismatik", "Berorientasi tujuan", "Tegas", "Analitis", "Kompetitif"],
    },
    "INTJ": {
        "kepanjangan": "Introverted, Intuitive, Thinking, Judging",
        "deskripsi": "INTJ adalah pemikir strategis yang independen dan berorientasi masa depan. Dijuluki 'The Architect' atau 'The Mastermind'.",
        "karakteristik": ["Visioner", "Kritis", "Mandiri", "Rasional", "Bertekad kuat"],
    },
    "ENTP": {
        "kepanjangan": "Extraverted, Intuitive, Thinking, Perceiving",
        "deskripsi": "ENTP adalah inovator yang cerdik, kritis, dan suka berdebat. Dijuluki 'The Debater' atau 'The Visionary'.",
        "karakteristik": ["Kreatif", "Kurang toleran terhadap rutinitas", "Pintar memecahkan masalah", "Eksperimental", "Karismatik"],
    },
    "INTP": {
        "kepanjangan": "Introverted, Intuitive, Thinking, Perceiving",
        "deskripsi": "INTP adalah pemikir abstrak yang logis dan suka teori. Dikenal sebagai 'The Logician' atau 'The Thinker'.",
        "karakteristik": ["Inovatif", "Analitis", "Objektif", "Skeptis", "Suka belajar"],
    },
    "ENFJ": {
        "kepanjangan": "Extraverted, Intuitive, Feeling, Judging",
        "deskripsi": "ENFJ adalah pribadi yang inspiratif, empatik, dan peduli pada perkembangan orang lain. Dijuluki 'The Protagonist' atau 'The Mentor'.",
        "karakteristik": ["Persuasif", "Altruistik", "Karismatik", "Harmonis", "Bertanggung jawab sosial"],
    },
    "INFJ": {
        "kepanjangan": "Introverted, Intuitive, Feeling, Judging",
        "deskripsi": "INFJ adalah tipe langka yang idealis, visioner, dan berkomitmen pada nilai-nilai. Dijuluki 'The Advocate' atau 'The Counselor'.",
        "karakteristik": ["Misterius", "Kreatif", "Determinasi kuat", "Empatik", "Spiritual"],
    },
    "ENFP": {
        "kepanjangan": "Extraverted, Intuitive, Feeling, Perceiving",
        "deskripsi": "ENFP adalah pribadi yang antusias, imajinatif, dan penuh ide. Dikenal sebagai 'The Campaigner' atau 'The Inspirer'.",
        "karakteristik": ["Energik", "Spontan", "Kreatif", "Sosial", "Optimis"],
    },
    "INFP": {
        "kepanjangan": "Introverted, Intuitive, Feeling, Perceiving",
        "deskripsi": "INFP adalah idealis yang penuh empati dan nilai-nilai pribadi kuat. Dijuluki 'The Mediator' atau 'The Healer'.",
        "karakteristik": ["Idealis", "Lembut", "Kreatif", "Setia pada prinsip", "Sensitif"],
    },
}